### ISSUE TITLE
# Sample State:

### ISSUE THREAD

**Issue by Evan-Leon** [yakzaetz/Avarts#4]
- [x] State shape is flat!
- [x] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ```javascript...```). This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
        - [x] entities
        - [x] session
        - [x] errors (here or in ui)
        - [x] ui (if needed)
    - [x] Should NOT have nested slices, aka comments inside of posts
        - Some info from other tables is ok, for instance:
            - the author username and imageurl for a post. basically any info that the user can’t change
            - like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by Evan-Leon** [comment]
Nice!
- should not have users password information or session token in users slice of state 
- will likely need latitude and longitude for routes, to be able to map them, may also need to do this for user location
- camel case for state shape instead snake

**Comment by yakzaetz** [comment]
with regard to to password_digest and session token I took them out. with regard to location I'm not yet familiar how to do this. hopefully will learn on the benchbnb project. otherwise please feel free to shoot some advice. I also fixed the camelCase where I noticed it

**Comment by Evan-Leon** [comment]
I think first step will be to figure out which map api to use: either Google maps or Mapbox.
Both have good docs and I would take a look to see which you prefer.
Likely for either you will need latitude and longitude to be able to plot the point on the map.
Essentially wherever you are thinking you need a location, think of it as latitude and longitude (DB and Frontend state)
