### ISSUE TITLE
# Backend Routes

### ISSUE THREAD

**Issue by Evan-Leon** [yakzaetz/Avarts#5]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in snake_case
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
- Ex. probably don't need a GET likes api endpoint because that info comes through the post show

**Comment by Evan-Leon** [comment]
Good work!
- change PUT to PATCH for updates
- consider getting rid of this route: GET, /api/users/:id/route
  - and bringing up a users routes when you bring up the user
- please include the sections HTML and API Endpoints (can look to the cohort wiki for reference)

**Comment by yakzaetz** [comment]
Fixed PUT to PATCH.
Got rid of that route.
Added HTML route

**Comment by Evan-Leon** [comment]
Nice changes!
