### ISSUE TITLE
# Frontend Routes

### ISSUE THREAD

**Issue by Evan-Leon** [yakzaetz/Avarts#6]
- [x] Frontend routes contains wildcard variables written in camelCase
- [x] Correctly formatted
- [x] Routes are displayed with inline coding text (backticks)

**Comment by Evan-Leon** [comment]
- please make a little more clear which routes/components will be available when logged in vs not logged in
- Looks good!

**Comment by yakzaetz** [comment]
Added a h2 for the components that can only be see when logged in

**Comment by Evan-Leon** [comment]
Excellent!
